services:
    mediamtx:
        build:
          context: .
          dockerfile: ./Dockerfile
        container_name: mediamtx
        hostname: mediamtx
        ports: ["1935:1935", "8889:8889", "8189:8189/udp", "8554:8554"]
        environment:
          - "STREAM_KEY_TEST=${STREAM_KEY_TEST}"
          - "STREAM_KEY=${STREAM_KEY}"
          - "STREAM_URL=${STREAM_URL}"
        volumes:
          - ./conf:/usr/local/mediamtx/conf
          - ./log:/usr/local/mediamtx/log
          - ./scripts:/usr/local/mediamtx/scripts


